### ISSUE TITLE
Initial set up

### ISSUE THREAD

**Issue by javhaan** [ec-intl/ptcolors#2]
```[tasklist]
### Tasks
- [x] Set up the devcontainer folder
- [x] Set up workflow folder
- [x] Add build_docs folder
- [x] Add environments folder
- [x] Add scripts folder
- [x] Add requirements folder
- [x] Add src folder
- [x] Update LICENSE
- [x] Update README
- [x] Add VERSION
```

**Comment by javhaan** [comment]
Completed 🌵
